#!/bin/bash
set -e -u -o pipefail
cd "$(dirname "$0")/.."
docker run --rm \
    -v "`pwd`:/cwd" \
    -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN \
    -e AWS_DEFAULT_REGION=ap-southeast-2 \
    realestate/stackup:1.2.1 leoren-notedump up -t cloudformation/s3.json